### ISSUE TITLE
Link to "buffer" example is broken

### ISSUE THREAD

**Issue by TimPietrusky** [dzduniak/shadertoy-svg#1]
The link to the "buffer" example is not working, as the corresponding shadertoy doesn't seem to exist. Would you mind to share another example?

**Comment by zduny** [comment]
Hi Tim.

Yes, I deleted my old ShaderToy account and forgot to re-upload the example and modify the link in the tool.
Here's the re-uploaded example: https://www.shadertoy.com/view/7lKGzR

I will try to modify the link in the tool later...  

EDIT: fixed (you may need to clear browser cache to see changes).

**Comment by TimPietrusky** [comment]
@zduny thank you very much! The buffer example is still killing my browser :D (But that is totally off topic)
